### ISSUE TITLE
I can't get the module working without the simulate option

### ISSUE THREAD

**Issue by YuenEsc** [flyandi/react-native-maps-navigation#2]
- The Boolean simulate doesn't affect the functionality of the library, I don't know if the library supports the navigation without being simulated, I'm still digging into the files but hadn't found anything yet. Also the animation aren't working properly

![](https://i.imgur.com/ZaPdmyB.png)
![](https://i.imgur.com/xwM2zKs.png)

**Comment by limaTobias** [comment]
I'm having the same problem, any updates?

**Comment by flyandi** [comment]
You mean you can't query live data from Google?

**Comment by noway** [comment]
Having the same issue. The question is how to get it out of demo mode?NavigationModes.NAVIGATION and this.refNavigation.navigateRoute() both drive the route themselves, it's not user driven.

**Comment by matikups** [comment]
Any updates on this?

**Comment by bestmazzo** [comment]
Hi, just sent a PR https://github.com/flyandi/react-native-maps-navigation/pull/7 on this issue

**Comment by flyandi** [comment]
PR accepted. Thank you!

**Comment by aaronbesson** [comment]
![ezgif-1-94fb70fdbc5f](https://user-images.githubusercontent.com/13420186/63308178-6fb22a00-c2bf-11e9-8cd6-ea302973b71a.gif)
Sorry to bump a closed issue... 
i disabled the simulator by commenting out the speed in Simulator.js. this way it still brings up the directions as well as rotates and tilts the map. But when you start to drive it does not update the directions/manoeuvres. it's not sensing the device has travelled. (gif attached is from actual device while driving)

I was wondering if you calculated speed using live data from the geolocation (in kmph or mph) it would update the manoeuvres/direction prompt?
