### ISSUE TITLE
Can We See The General Usage

### ISSUE THREAD

**Issue by Yingi** [flyandi/react-native-maps-navigation#5]
I tried using this library, but my screen is blank. Can i at least see how to use this library basically. You didnt put anything in your General Usage. Please!!!!!

**Comment by craftdelivery** [comment]
Try Setting the width and height for the map in a styles object

**Comment by flyandi** [comment]
There is a full working example in https://github.com/flyandi/react-native-maps-navigation-example - however I am still working on this  but it got stalled a bit - will be catching up sometime in July.
