### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by matikups** [flyandi/react-native-maps-navigation#6]
Hi
I'm trying out this library but it's far away for production usage.
It works by simulating, yet not in real case.

And it has been 11 months since the last commit.
I'm trying to get it working in production, learning everything, but I'd like to see if there's a new release/commit comming or it wont be maintained no more.

Thanks

**Comment by flyandi** [comment]
Barely - I am maintaining a copy in my internal prod apps but the OS version lacks behind due to time constrains. Happy to accept PR's.
